### ISSUE TITLE
Getting (PyDeltaTableError: Not a Delta table: No snapshot or version 0 found) exception reading from Azure blob storage

### ISSUE THREAD

**Issue by theyaa** [delta-io/delta-rs#564] opened 2022-02-25 16:32 UTC
# Environment
Azure
**Delta-rs version**: 0.5.6

**Binding**: Azure

**Environment**: python
- **Cloud provider**: Azure
- **OS**: Windows
- **Other**:

***
# Bug

**What happened**:
Trying to query deltalake from azure blob storage given the below example but getting exception.

%env "AZURE_STORAGE_ACCOUNT_NAME"="account_name"
%env "AZURE_STORAGE_ACCOUNT_KEY"="access_key"
options={"AZURE_STORAGE_ACCOUNT_NAME":"account_name", "AZURE_STORAGE_ACCOUNT_KEY":"access_key"}
df = DeltaTable('/path/delta/data', storage_options=options)

Getting the below exception.
PyDeltaTableError: Not a Delta table: No snapshot or version 0 found, perhaps /path/delta/data is an empty dir?

**What you expected to happen**:

**How to reproduce it**:

**More details**:

**Comment by roeap** [comment] 2023-01-25 13:56
@theyaa - just to clarify, is there a table present at the specified location or do you ant to create one?

@McSash - the `DeltaTable` class right now does not expose any write / create operations, rather this should be done via the `write_deltatable` function exposed in `deltalake.writer`. After the table has ben created / written to the first time, you should be able to read it using `DeltaTable`.

**Comment by ion-elgreco** [comment] 2023-10-08 18:23
I think the issue can be closed. You usually get this error when there is no table

**Comment by roeap** [comment] 2023-10-17 19:21
Closing this as this is by now part of the integration tests and underlying object store is extensively tested. Feel free to re-open if the issue persists, but I could not reproduce.

**Closed by roeap** 2023-10-17 19:21 UTC
Labels: bug
