### ISSUE TITLE
Broken filter for newly created delta table

### ISSUE THREAD

**Issue by Hanspagh** [delta-io/delta-rs#2169] opened 2024-02-06 13:18 UTC
# Environment

**Delta-rs version**:
'0.15.2'

**Binding**: 
python

**Environment**:
- **OS**: Mac 

***
# Bug

When creating a new delta table from a pandas dataframe, it appears that the filter predicate is broken for some expression 

**What happened**:
.to_pandas() and .to_pyarrow_dataset() return 0 data

**What you expected to happen**:
The above functions should return the data reflected in the filter predicate

**How to reproduce it**:
This is a large dataset that I cannot share, but please point me in any directions for how to debug this.

This is how I achieved my current results

```python
from pyarrow import dataset as ds
from pyarrow.parquet import ParquetFile, ParquetDataset
import pyarrow.compute as pc
from deltalake import write_deltalake, convert_to_deltalake, DeltaTable
import pandas as pd

df = "some_internal_data"

write_deltalake("broken_nlrot.delta", df)

dt_broken = DeltaTable("broken_nlrot.delta")
dt_broken.to_pyarrow_dataset().to_table(filter=(pc.field("terminal") == "NLROTTM")).shape
# returns (0, 19)

# Trying to read strait with pyarrow
ds.dataset("broken_nlrot.delta").to_table(filter=(pc.field("terminal") == "NLROTTM")).shape
# returns (773536, 19) which is the expected result

#similarly to_pandas also does not seem to work 
dt_broken.to_pandas(filters=[("terminal", "==", "NLROTTM")]).shape 
# returns (0,19)

# again with pyarrow we are fine
ParquetDataset("broken_nlrot.delta", filters=[("terminal", "==", "NLROTTM")]).read().shape
# returns (773536, 19) which is the expected result

#oddly enough it seems to work when I choose a different filter predicate I dont get zero rows, but still wrong resulst
dt_broken.to_pandas(filters=[("terminal", "==", "USSAVGC")]).shape
# (89406, 19) - Wrong

ds.dataset("broken_nlrot.delta").to_table(filter=(pc.field("terminal") == "USSAVGC")).shape
# (420029, 19) - Correct

# pulling the full data in pandas also seems to work
full = dt_broken.to_pandas()
full[full["terminal"] == "NLROTTM"].shape
# (773536, 19)

full[full["terminal"] == "USSAVGC"].shape
# (420029, 19)


# calling optimize seem to fix the problem, but this should not be needed in order for filters to work
dt.optimize.z_order(["terminal"])
dt_broken.to_pyarrow_dataset().to_table(filter=(pc.field("terminal") == "NLROTTM")).shape
# returns (773536, 19)


```

Since this is returning partially correct results, I suspect maybe some row_group statistics being wrong, but then I would assume the calls from pyarrow would also return incorrect results

**Comment by ion-elgreco** [comment] 2024-02-06 14:03
@Hanspagh can you please check the following things:

- try ` write_deltalake(engine='rust')` since this eliminates pyarrow from the equation (also please share the pyarrow version you use now)
- try deltalake v0.15.1 or v0.15.0

Also, it would really help if you can mimic the structure of the data with fake/sample data so we can try to reproduce, the only logical thing I can think off for now is the partition expression is incorrect

**Comment by Hanspagh** [comment] 2024-02-06 14:36
Sure, let me try those suggestions first, then I can try to see if I can
reproduce the problem with a smaller subset

**Comment by Hanspagh** [comment] 2024-02-06 15:24
Okay, so this seem to be related to pyarrow since engine="rust" fixes this.
Currently, I am using Pyarrow 13.0.0

**Comment by Hanspagh** [comment] 2024-02-06 16:26
So I managed to reproduce this. It only happens with large dataset 10_485_761 seems to be the magic number, I tried both with pyarrow 13, 15, 12, all seems to have the problem. With Pyarrow 8 the process seems to hang when I try to save a dataset this large.

It looks as the filter overflows and only returns the rows that large than 10_485_760, since we get 1 for 10_485_761 and 2 for 10_485_762

I hope this helps to figure out what is going on here. Let me know if you want me to provide more details

```
df = pd.DataFrame({"data": ["B"] * 10_485_760 })
write_deltalake("sample.delta", df, mode="overwrite")
dt_broken = DeltaTable("sample.delta")
dt_broken.to_pyarrow_dataset().to_table(filter=(pc.field("data") == "B")).shape
# (10485760, 1)

df = pd.DataFrame({"data": ["B"] * 10_485_761 })
write_deltalake("sample.delta", df, mode="overwrite")
dt_broken = DeltaTable("sample.delta")
dt_broken.to_pyarrow_dataset().to_table(filter=(pc.field("data") == "B")).shape
# (1, 1)

df = pd.DataFrame({"data": ["B"] * 10_485_762 })
write_deltalake("sample.delta", df, mode="overwrite")
dt_broken = DeltaTable("sample.delta")
dt_broken.to_pyarrow_dataset().to_table(filter=(pc.field("data") == "B")).shape
# (2, 1)

```

**Comment by Hanspagh** [comment] 2024-02-06 16:41
I found the magic number, it comes from the default of `max_rows_per_file` in write_deltalake, which is set to 1024*1024*10, I suggest this to be aligned with pyarrow where the default is None/0

**Comment by ion-elgreco** [comment] 2024-02-06 16:48
@Hanspagh there seems to be an issue with the creation of the pyarrow.dataset when data got sharded. I can write tables with v0.15.2 and then read them with v0.15.1 with the pc.field("data")=="B" expression.

**Comment by Hanspagh** [comment] 2024-02-06 17:01
Hmm, but it does not seem to be strictly related to number of files

this works fine
```python
df = pd.DataFrame({"data": ["B"] * 10 })
write_deltalake("broken.delta", df, max_rows_per_file=2, max_rows_per_group=2, min_rows_per_group=2)
# 5 output files
dt_broken = DeltaTable("/Users/hans.pagh/Downloads/broken.delta")
dt_broken.to_pyarrow_dataset().to_table(filter=(pc.field("data") == "B")).shape
# (10,1)
```

**Comment by ion-elgreco** [comment] 2024-02-06 17:06
@Hanspagh I see the issue, the stats are empty on the add action for one of the files, will have to check why they are empty now and not before : )

**Comment by Hanspagh** [comment] 2024-02-06 17:18
This seems to one of the smaller examples, where it is broken
``` python
df = pd.DataFrame({"data": ["B"] * 1024 * 33 })
write_deltalake("broken.delta", df, max_rows_per_file=1024*32,max_rows_per_group=1024 * 16, min_rows_per_group=8*1024, mode="overwrite")
```

This seems fine, so there is something up with the multiplier for the max/min

```python
df = pd.DataFrame({"data": ["B"] * 1024 * 37 })
write_deltalake("broken.delta", df, max_rows_per_file=1024*36,max_rows_per_group=1024 * 18, min_rows_per_group=9*1024, mode="overwrite")
```

**Comment by ion-elgreco** [comment] 2024-02-06 17:39
@Hanspagh you mean the rust engine?

**Comment by ion-elgreco** [comment] 2024-02-06 18:16
@Hanspagh not sure, I think they originated from some defaults databricks does with spark-delta. 

Fix is incoming btw

**Closed** 2024-02-06 18:42 UTC
Labels: bug
