### ISSUE TITLE
Cannot load version properly if there exists corresponding checkpoint

### ISSUE THREAD

**Issue by ognis1205** [delta-io/delta-rs#1403] opened 2023-05-29 02:31 UTC
# Environment

**Delta-rs version**:
v.0.11.0

**Binding**: 
Python

**Environment**:
- **Cloud provider**: N/A
- **OS**: macOS Monterey Version 12.3.1
- **Other**:

***
# Bug

**What happened**:
The [load_version](https://github.com/delta-io/delta-rs/blob/106ad1282e1b0963e0cd7c0c4a74e0f29efa1d75/rust/src/delta.rs#L877) does not work correctly when there exists the corresponding checkpoint of the user specified version. This is due to [the condition](https://github.com/delta-io/delta-rs/blob/106ad1282e1b0963e0cd7c0c4a74e0f29efa1d75/rust/src/delta.rs#L860) is always evaluated as `false`.

**What you expected to happen**:
The [load_version](https://github.com/delta-io/delta-rs/blob/106ad1282e1b0963e0cd7c0c4a74e0f29efa1d75/rust/src/delta.rs#L877) loads a specified version of a table particularly when there exists the corresponding checkpoint.

**How to reproduce it**:
[Notebooks](https://github.com/ognis1205/delta-rs-playground/tree/main/notebooks)

**More details**:
```bash
 $ tree _delta_log 
_delta_log
├── 00000000000000000000.checkpoint.parquet
├── 00000000000000000000.json
├── 00000000000000000001.json
├── 00000000000000000002.json
├── 00000000000000000003.json
├── 00000000000000000004.json
├── 00000000000000000005.json
├── 00000000000000000006.json
├── 00000000000000000007.json
├── 00000000000000000008.json
├── 00000000000000000009.json
├── 00000000000000000010.checkpoint.parquet
├── 00000000000000000010.json
:
```

**Comment by rtyler** [comment] 2024-01-03 04:01
I believe this is fixed, can you verify please?

**Comment by alexwilcoxson-rel** [comment] 2024-01-11 22:48
I don't believe it is, if you look at [load_version](https://github.com/delta-io/delta-rs/blob/f7c303b74218c202ef683f727701a67da5aaaca5/crates/deltalake-core/src/table/mod.rs#L600), if the requested version is a checkpoint the state will get updated from the checkpoint, then when [update_incremental](https://github.com/delta-io/delta-rs/blob/f7c303b74218c202ef683f727701a67da5aaaca5/crates/deltalake-core/src/table/mod.rs#L544) is called it performs a [check](https://github.com/delta-io/delta-rs/blob/f7c303b74218c202ef683f727701a67da5aaaca5/crates/deltalake-core/src/table/mod.rs#L554) to see which version to load up to, however the table state version will equal the version requested and "fail" the check falling into getting the whole table state.

After loading the checkpoint if the table's version is equal to the requested update_incremental could not be called by load_version or itself could exit early.

**Comment by ion-elgreco** [comment] 2024-08-19 19:54
I can't reproduce this anymore, so closing the issue

**Closed by ion-elgreco** 2024-08-19 19:54 UTC
Labels: bug
