### ISSUE TITLE
Investigate atomic rename failure on Linux/aarch64

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#172] opened 2021-03-30 05:33 UTC
My hunch is that this is related to our glibc crate that we're depending on nowadays.

```
tyler in coconut in delta-io/delta.rs/rust took 2m3s
❯ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.39s
     Running /home/tyler/source/github/delta-io/delta-rs/target/debug/deps/deltalake-447ca4f636100e9e

running 6 tests
test storage::file::tests::join_multiple_paths ... ok
test storage::tests::test_parse_uri_local_file ... ok
test action::tests::test_load_table_stats ... ok
test storage::file::rename::tests::test_atomic_rename ... FAILED
test storage::file::tests::put_obj ... ok
test action::tests::test_add_action_without_partition_values_and_stats ... ok

failures:

---- storage::file::rename::tests::test_atomic_rename stdout ----
thread 'storage::file::rename::tests::test_atomic_rename' panicked at 'assertion failed: `(left == right)`
  left: `"failed to rename not_exists to /tmp/test_atomic_rename.QRWkjCyHbnml/c: Invalid cross-device link"`,
 right: `"failed to rename not_exists to /tmp/test_atomic_rename.QRWkjCyHbnml/c: No such file or directory"`', rust/src/storage/file/rename.rs:100:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    storage::file::rename::tests::test_atomic_rename

test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

error: test failed, to rerun pass '--lib'

tyler in coconut in delta-io/delta.rs/rust
❯ uname -a
Linux coconut 5.6.14-1-default #1 SMP Wed May 20 08:32:48 UTC 2020 (b0ab48a) aarch64 aarch64 aarch64 GNU/Linux

tyler in coconut in delta-io/delta.rs/rust
❯ rustc --version
rustc 1.51.0 (2fd73fabe 2021-03-23)

```

**Comment by mosyp** [comment] 2021-03-30 12:10
It is caused by the fact that `/tmp` is on another device to the current working dir. 

```rust
        let tmp_dir = tempdir::TempDir::new("test_atomic_rename").unwrap();
        let a = create_file(&tmp_dir.path(), "a");
        let b = create_file(&tmp_dir.path(), "b");
        let c = &tmp_dir.path().join("c");

        // unsuccessful move not_exists to C, not_exists is missing
        match atomic_rename("not_exists", c.to_str().unwrap()) {
```

I feel like this might be fixed by changing it to:
```rust
 match atomic_rename(&tmp_dir.path().join("not_exists").to_str().unwrap(), c.to_str().unwrap()) {
```

so `not_exists` would be on the same drive

**Comment by mosyp** [comment] 2021-03-30 12:19
@rtyler Please verify that `/tmp/` is mounted on other device.

That might be 
```
EXDEV  oldpath and newpath are not on the same mounted
              filesystem.  (Linux permits a filesystem to be mounted at
              multiple points, but rename() does not work across
              different mount points, even if the same filesystem is
              mounted on both.)
```

@houqp I feel like we should add also a flag to the error mapping, because `Invalid cross-device link` might not be enough, having it as `EXDEV: Invalid cross-device link` would make debug easier

**Comment by mosyp** [comment] 2021-03-30 12:21
(btw, this is the main reason why we store tmp file within table dir, but not in `/tmp`, since we cannot guarantee that it is not mounted)

**Comment by rtyler** [comment] 2021-03-30 16:13
Yes this is a different device, I think it's _relatively_ common for some non-Debian based distributions to use `tmpfs` for `/tmp`

```
tmpfs            15G  1.7G   13G  12% /tmp
```

**Comment by houqp** [comment] 2021-03-31 01:10
@mosyp yep, we should either change the `not_exists` file path to tmp dir or change current working dir to temp dir within the test.

I am just surprised that the kernel would check the mount points for both paths first, I was expecting it to check the source path and error out immediately without proceeding to validate the mount points for both directories :P

**Closed** 2021-04-04 22:59 UTC
Labels: binding/rust, bug, good first issue, help wanted
