### ISSUE TITLE
Invalid JSON in log record missing field `schemaString` for DLT tables

### ISSUE THREAD

**Issue by abhilashsharma1992** [delta-io/delta-rs#1302] opened 2023-04-20 09:24 UTC
# Environment
Databricks DLT 

**Delta-rs version**: [rust-v0.8.0](https://github.com/delta-io/delta-rs/releases/tag/rust-v0.8.0)

**Binding**:  [python-v0.8.1](https://github.com/delta-io/delta-rs/releases/tag/python-v0.8.1)

**Environment**:
- **Cloud provider**: Azure
- **OS**: Ubuntu
- **Other**: Specifically observing for Delta Live Tables

***
# Bug
**What happened**:  Seeing an error while loading a ADLS delta table, please find the code snippet
    storage_options = {

        "AZURE_STORAGE_ACCOUNT_KEY": tenant_storage_access_key,

        "AZURE_STORAGE_ACCOUNT_NAME": tenant_storage_account_name

    }

    dt = DeltaTable(deltaPathName,storage_options=storage_options)

Exception Stack trace:

Traceback (most recent call last): File "<string>", line 1, in <module> File "/home/ankit/spc-data-analytics/src/lakehousechangedatacapture/.venv/lib/python3.8/site-packages/deltalake/table.py", line 122, in __init__ self._table = RawDeltaTable( deltalake.PyDeltaTableError: Invalid JSON in log record, version=0, line=`{"metaData":{"id":"ac0a0120-970e-4d8c-ae92-b5244b055d6e","format":{"provider":"parquet","options":{}},"partitionColumns":[],"configuration":{},"createdTime":1681798577757}}`, err=`missing field `schemaString` at line 1 column 171`

**What you expected to happen**: DeltaTable class should load the ADLS delta table, all other delta tables other than DLT tables are working as expected

**How to reproduce it**: Create a DLT table in ADLS and read using python binding(as shown in code above).

**More details**:
Summary: Azure Databricks DLT pipeline used to write to ADLS everyday, subsequently read from Delta-rs python binding which is failing to load.

**Comment by roeap** [comment] 2023-04-20 23:38
Personally I never worked with live tables, but it is surprising that we do not have a schema defined in the shown log record.

Could you check the log for version 1 to see if that contains a schema definition?

**Comment by abhilashsharma1992** [comment] 2023-04-21 09:33
Please find the first two log files for the delta table:
**1st:**
{"commitInfo":{"timestamp":1681798578373,"operation":"DLT REFRESH","operationParameters":{"pipelineId":"5c7b47e9-12d6-4986-a601-6716734281ce","updateId":"adf780f9-789f-4857-8d41-e4d9938b61d5"},"isolationLevel":"WriteSerializable","isBlindAppend":false,"operationMetrics":{},"engineInfo":"Databricks-Runtime/dlt:11.3-delta-pipelines-801d604-ff1aff6-f0f113d-custom-local","txnId":"a2ad05c8-4559-41bc-b7b1-a94773bd2286"}}

{"protocol":{"minReaderVersion":1,"minWriterVersion":2}}

{"metaData":{"id":"ac0a0120-970e-4d8c-ae92-b5244b055d6e","format":{"provider":"parquet","options":{}},"partitionColumns":[],"configuration":{},"createdTime":1681798577757}}


**2nd:**
{"commitInfo":{"timestamp":1681798612850,"operation":"DLT SETUP","operationParameters":{"pipelineId":"5c7b47e9-12d6-4986-a601-6716734281ce","updateId":"adf780f9-789f-4857-8d41-e4d9938b61d5"},"readVersion":0,"isolationLevel":"WriteSerializable","isBlindAppend":false,"operationMetrics":{},"engineInfo":"Databricks-Runtime/dlt:11.3-delta-pipelines-801d604-ff1aff6-f0f113d-custom-local","txnId":"c1e3c149-d6b1-4a51-b7a6-89c328d14833"}}

{"protocol":{"minReaderVersion":2,"minWriterVersion":5}}

{"metaData":{"id":"ac0a0120-970e-4d8c-ae92-b5244b055d6e","name":"SnowflakeTest_Snowflake_DTL_SHERPA_USER_TABLE","format":{"provider":"parquet","options":{}},"schemaString":"{\"type\":\"struct\",\"fields\":[{\"name\":\"sherpa_user_id\",\"type\":\"decimal(38,0)\",\"nullable\":true,\"metadata\":{}},{\"name\":\"enabled\",\"type\":\"boolean\",\"nullable\":true,\"metadata\":{}},{\"name\":\"last_login\",\"type\":\"timestamp\",\"nullable\":true,\"metadata\":{}},{\"name\":\"first_name\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"last_name\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"full_name\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"email\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"job_title\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"hire_date\",\"type\":\"date\",\"nullable\":true,\"metadata\":{}},{\"name\":\"skypoint_delta_index\",\"type\":\"long\",\"nullable\":true,\"metadata\":{}}]}","partitionColumns":[],"configuration":{"pipelines.pipelineId":"5c7b47e9-12d6-4986-a601-6716734281ce","pipelines.autoOptimize.managed":"false","pipelines.metastore.tableName":"`automation_retailsandbox`.`SnowflakeTest_Snowflake_DTL_SHERPA_USER_TABLE`"},"createdTime":1681798577757}}

**Comment by roeap** [comment] 2023-04-21 19:02
interesting, it seems DLT does not create the schema, when it creates the table. this should be a straight forward fix though, since reading the schema is already a fallible operation. I'll fix this shortly.

Thanks for reporting!

**Comment by abhilashsharma** [comment] 2023-07-28 11:20
@roeap thanks for working on this, i see the PR is created to fix this. When can we expect this to be merged and release.

**Comment by a-martikainen** [comment] 2023-08-30 12:04
There seems to also be a recent duplicate of this issue here: https://github.com/delta-io/delta-rs/issues/1557

We have also encountered the same issue with one DLT table, where one metadata version in the middle of history for some reason has an empty schema field, causing this error for the library. (see discussion about the issue here: https://github.com/delta-io/delta-rs/discussions/1604 )

**Comment by rtyler** [comment] 2023-09-25 17:06
Fix will be in the next release

**Closed by rtyler** 2023-09-25 17:06 UTC
Labels: bug, binding/rust

**Comment by ankit-skypoint** [comment] 2023-10-17 02:53
Hi @rtyler @roeap @a-martikainen, I am a colleague of @abhilashsharma.
We are still facing this issue for DLT tables using the latest deltalake version 0.11.0.
Please find the following error:

Traceback (most recent call last):
[2023-10-12T13:58:53.649Z]   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
[2023-10-12T13:58:53.649Z]     self.run()
[2023-10-12T13:58:53.650Z]   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
[2023-10-12T13:58:53.650Z]     self._target(*self._args, **self._kwargs)
[2023-10-12T13:58:53.650Z]   File "/home/ankit/spc-data-analytics/src/lakehousechangedatacapture/service_bus_cdc/__init__.py", line 375, in change_data_capture
[2023-10-12T13:58:53.650Z]     dt = DeltaTable(deltaPathName,storage_options=storage_options)
[2023-10-12T13:58:53.650Z]   File "/home/ankit/spc-data-analytics/src/lakehousechangedatacapture/.venv/lib/python3.8/site-packages/deltalake/table.py", line 247, in __init__
[2023-10-12T13:58:53.650Z]     self._table = RawDeltaTable(
[2023-10-12T13:58:53.651Z] _internal.DeltaError: Delta protocol violation: Invalid action field: type for schemaString in metaData action should be string
