### ISSUE TITLE
DataCatalog does not work for the Python binding

### ISSUE THREAD

**Issue by everdark** [delta-io/delta-rs#1466] opened 2023-06-15 05:02 UTC
# Environment

**Delta-rs version**: 0.10.0

**Binding**: Python

**Environment**:
- **Cloud provider**: AWS
- **OS**: macOS 13.4 (Intel chip)

***
# Bug

**What happened**:

When running 

```python
DeltaTable.from_data_catalog(DataCatalog.AWS, "dbname", "tablename")
```
the following error is raised:

```
--> 264         table_uri = RawDeltaTable.get_table_uri_from_data_catalog(
    265             data_catalog=data_catalog.value,
    266             data_catalog_id=data_catalog_id,

ValueError: Catalog 'glue' not available.
```

AWS credentials have been properly setup as environment variable.
Delta table has been properly registered by crawler.
And within the same session, we have no issue fecthing the table info using AWS SDK:

```python
import boto3
client = boto3.client('glue')
client.get_table(DatabaseName="dbname", Name="tablename")
```

Also a direct instantiation from s3 path works as well:

```python
DeltaTable("s3://path/to/table")
```

**What you expected to happen**:

`DeltaTable.from_data_catalog` should return a `DeltaTable` instance based on catalog supported. In this case, it is AWS Glue.

As a side note, I also hear from other folks facing the same error when using UNITY catalog.

**Comment by arabe91** [comment] 2023-06-28 15:06
i can confirm that I have exactly the same issue while using the UNITY catalog

**Comment by wjones127** [comment] 2023-06-28 15:19
Thanks for reporting this. I think we'll need some help from folks who know more about catalogs; we don't have integration tests with them yet since we aren't sure how to set them up.

**Comment by rtyler** [comment] 2024-01-06 19:47
I'm going to close this, since we removed that functionality.

**Closed by rtyler** 2024-01-06 19:47 UTC
Labels: bug, help wanted
