### ISSUE TITLE
Cant create empty table with write_deltalake

### ISSUE THREAD

**Issue by Mxater** [delta-io/delta-rs#2086] opened 2024-01-16 20:08 UTC
# Environment
Windows 11 
Python 3.11
Pandas 2.1.4
**Delta-rs version**: 0.15

**Environment**: Local
- **OS**: Windows 11

***
# Bug

**What happened**:
I tried to create a new empty table in datalake, this is code:

```
columnas = ['fecha', 'fecha_archivo', 'fecha_archivo_string', 'filename', 'registros', 'cliente', 'retail', 'ejecucion', 'cargado', 'estado', 'observacion', 'dias_quiebre', 'inmovilizados', 'dias_inmovilizados']

df = pd.DataFrame(columns=columnas)
write_deltalake(rutaBase + "filestest", df, mode="overwrite")
```
Throw the next error:

```
Traceback (most recent call last):
  File "X:\Asyma\Python\FabricProcess\pythonProject\test2.py", line 45, in <module>
    write_deltalake(rutaBase + "filestest", df, mode="overwrite")
  File "C:\Python311\Lib\site-packages\deltalake\writer.py", line 325, in write_deltalake
    raise ValueError(
ValueError: Schema of data does not match table schema
Data schema:
fecha: null
fecha_archivo: null
fecha_archivo_string: null
filename: null
registros: null
cliente: null
retail: null
ejecucion: null
cargado: null
estado: null
observacion: null
dias_quiebre: null
inmovilizados: null
dias_inmovilizados: null
Table Schema:
fecha: timestamp[us]
fecha_archivo: timestamp[us]
fecha_archivo_string: timestamp[us]
filename: timestamp[us]
registros: timestamp[us]
cliente: timestamp[us]
retail: timestamp[us]
ejecucion: timestamp[us]
cargado: timestamp[us]
estado: timestamp[us]
observacion: timestamp[us]
dias_quiebre: timestamp[us]
inmovilizados: timestamp[us]
dias_inmovilizados: timestamp[us]
__index_level_0__: int64
```

**Comment by ion-elgreco** [comment] 2024-01-20 09:21
The reason it throws an error is because your Pandas dataframe has columns with no dtype so it's inferred as null. So converting this to a pyarrow table will give this schema: 

```python
pa.Table.from_pandas(df).schema

fecha: null
fecha_archivo: null
fecha_archivo_string: null
filename: null
registros: null
cliente: null
retail: null
ejecucion: null
cargado: null
estado: null
observacion: null
dias_quiebre: null
inmovilizados: null
dias_inmovilizados: null
```

I am closing this since this is not a bug, you need to instantiate your pandas dataframe with the correct dtypes using the dtype argument.

**Closed** 2024-01-20 09:22 UTC
Labels: bug

**Comment by Mxater** [comment] 2024-01-22 16:05
I dont find the way to instantiate the pandas dataframes with dtypes column. Can you help me with that?
