### ISSUE TITLE
Merge function generating duplicated in the target table

### ISSUE THREAD

**Issue by PecTheFabricator** [delta-io/delta-rs#2961] opened 2024-10-24 21:51 UTC
# Environment

**Delta-rs version**: 0.20.2

**Binding**: 

**Environment**:
- **Cloud provider**: Azure
- **OS**: Linux
- **Other**:

***
# Bug

**What happened**:

In the merge function, if the source has duplicated value, it will duplicate the values in the target table instead of throwing an error like in spark version.

**What you expected to happen**:

Throw an error like spark version.

**How to reproduce it**:

In the merge function, pass in the source, a source with duplicated value. The duplicated needs to persists adding the predicate.

**More details**:

**Comment by ion-elgreco** [comment] 2024-10-25 05:15
Duplicate of https://github.com/delta-io/delta-rs/issues/2407

**Closed by ion-elgreco** 2024-10-25 05:15 UTC
Labels: bug
