### ISSUE TITLE
Upsert into delta table

### ISSUE THREAD

**Issue by moria97** [delta-io/delta-rs#752] opened 2022-08-18 06:38 UTC
# Description
Currently write to delta table interface implements both append and overwrite mode. But seems overwrite mode can only remove all data and append new data. A typical Upsert scenario is not supported here. Do we have any plans to support overwrite based on some predicates?

**Use Case**
Update existing data. Not just append.

**Related Issue(s)**
None

**Comment by roeap** [comment] 2022-08-18 07:00
Yes, the plan is to support this. I want to get to implement some more higher level write APIs soon-ish, but there are some priorities that need to get done first.

**Comment by moria97** [comment] 2022-08-18 07:09
@roeap Do we have any timeline for the feature?
Or do we have any tech docs/wikis for reference? Maybe I can start with my own version first:)

**Comment by roeap** [comment] 2022-08-18 09:06
are you using the python APIs, or the rust API directly.

**Comment by moria97** [comment] 2022-08-18 15:39
I'm using the rust API, actually I'm writing dotnet and plan to interop rust code from .net.
By the way, is there any plan for delete operation? Maybe this is also related to Upsert as the logic seems similar

**Comment by davidgasquez** [comment] 2022-10-14 14:42
Hey there! Curious about the state/priority of this issue. :eyes:

**Comment by wjones127** [comment] 2022-10-14 14:51
Operations like this (that rewrite data) are in [our backlog](https://github.com/delta-io/delta-rs/blob/main/CONTRIBUTING.md#backlog) right now. We are currently refactoring our writing APIs for now, and once that's done this should be ready for someone to take on. But I don't think there is yet a contributor who has volunteered to work on this.

**Comment by jordandakota** [comment] 2023-05-11 06:15
@Blajda @wjones127 
Now that delete operation seems to be working, any thoughts on this next?

**Comment by Blajda** [comment] 2023-05-11 16:59
Hi @jordandakota to me Upserts are a special case of the Merge operation which is being tracked at #850.
Is there anything that merge will miss once it is implemented?

I plan to work on the update command next and will start to focus more on merge afterwards.

**Comment by jordandakota** [comment] 2023-05-13 02:23
No, merge probably covers a larger use case. Insert Overwrite and replaceWhere are important, but mostly so for very large datasets. We can already obtain upsets in two transactions.

**Comment by ion-elgreco** [comment] 2023-10-08 18:47
@wjones127 @rtyler maybe close this one since its a duplicate of: https://github.com/delta-io/delta-rs/issues/850

**Closed** 2023-11-06 21:22 UTC
Labels: enhancement
