### ISSUE TITLE
write delta table on GCP, works fine but error on log file

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#878] opened 2022-10-11 11:08 UTC
# Environment

0.6.2

python

GCP 

***
# Bug
using this code
write_deltalake("gs://xxxx", df,partition_by=['Date'], mode='append')

the folders, parquet are created correctly but there is an error when it try to write the log file

PyDeltaTableError: Failed to read delta log object: Generic GCS error: Error performing copy request _delta_log/_commit_1237998f-12a2-460b-9383-65e3c9dc036f.json.tmp: response error "<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 411 (Length Required)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//[www.google.com/images/errors/robot.png](http://www.google.com/images/errors/robot.png)) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//[www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png](http://www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png)) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//[www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png](http://www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png)) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//[www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png](http://www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png)) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//[www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png](http://www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png)) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//[www.google.com/](http://www.google.com/)><span id=logo aria-label=Google></span></a>
  <p><b>411.</b> <ins>That’s an error.</ins>
  <p>POST requests require a <code>Content-length</code> header.  <ins>That’s all we know.</ins>
", after 0 retries: HTTP status client error (411 Length Required) for url ([https://storage.googleapis.com/storage/v1/b/aemo3/o/%5Fdelta%5Flog%2F%5Fcommit%5F1237998f%2D12a2%2D460b%2D9383%2D65e3c9dc036f%2Ejson%2Etmp/copyTo/b/aemo3/o/%5Fdelta%5Flog%2F00000000000000000000%2Ejson?ifGenerationMatch=0](https://storage.googleapis.com/storage/v1/b/aemo3/o/_delta_log%2F_commit_1237998f-12a2-460b-9383-65e3c9dc036f.json.tmp/copyTo/b/aemo3/o/_delta_log%2F00000000000000000000.json?ifGenerationMatch=0))

**Comment by JasperHG90** [comment] 2022-10-15 13:44
Running into the same problem when attempting to write to a GCS bucket. Should note that you only run into this if you set the environment variable SERVICE_ACCOUNT. Else, it fails because `storage_options` is not passed to `try_get_deltatable` in [writer.py](https://github.com/delta-io/delta-rs/blob/main/python/deltalake/writer.py#L332) even if you pass it to the `write_deltalake` function.

**Comment by djouallah** [comment] 2022-11-10 03:40
same error in 0.6.3 :(

**Comment by rando-brando** [comment] 2022-11-22 18:56
I get a similar error when trying to use a local file system "file://xxxx".

`deltalake.PyDeltaTableError: Failed to read delta log object: Generic DeltaLocalObjectStore error: Function not implemented (os error 38)`

If I try to specify a LocalFilesystem I get: `NotImplementedError: Filesystem support is not yet implemented.`

**Comment by djouallah** [comment] 2022-11-29 22:52
@wjones127 the json is not written at all, all I get is the tmp file , which corrupt the table

**Comment by wjones127** [comment] 2022-11-30 05:48
I haven't been able to reproduce that error yet. But I have reported the underlying error upstream in apache/arrow-rs#3235.

**Comment by wjones127** [comment] 2022-12-04 23:58
We weren't able to reproduce the described error in the upstream object store. I don't think it originated as described in the error report, since the header doesn't seem to be actually required in the GCS API.

I did confirm that writing to GCS doesn't seem to be working, so there is an issue. However, the error I am seeing is related to the multi-part upload, not the copy:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wjones/delta-rs/python/deltalake/writer.py", line 255, in write_deltalake
    ds.write_dataset(
  File "/home/wjones/delta-rs/python/venv/lib/python3.10/site-packages/pyarrow/dataset.py", line 985, in write_dataset
    _filesystemdataset_write(
  File "pyarrow/_dataset.pyx", line 2775, in pyarrow._dataset._filesystemdataset_write
deltalake.PyDeltaTableError: response error "<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message><Details>Invalid argument.</Details></Error>", after 0 retries: HTTP status client error (400 Bad Request) for url (https://storage.googleapis.com/wjones127%2Dtest%2Dobject%2Dstore%2Drs/delta%2Dtest2%2F0%2D27c439aa%2Dc758%2D444f%2Db367%2D01e41499f23f%2D0%2Eparquet?uploadId=ABPnzm6GyXLl31OhysNHaOwsnI_mFrNDh-pjxzGaSRyDmBJF6-VO9bV9LZx8mNQH2pkFkYE)
```

<details>
<summary>Code to repro</summary>

```python
from deltalake import write_deltalake
import pyarrow as pa
from numpy.random import default_rng

random = default_rng()

tab = pa.table({
    "x": random.normal(size=5 * 1024 * 1024)
})

write_deltalake(
    "gs://wjones127-test-object-store-rs/delta-test2/",
    tab,
)
```
</details>

I'll be on vacation for a couple weeks, so won't have time to look into this for a little while. If someone else has some time to investigate, that would be appreciated :)

**Comment by wjones127** [comment] 2023-01-26 04:53
I am now able to reproduce the original error in delta-rs, but still not having luck reproducing using the underlying object store implementation. I've ruled out it being related to the file name or the size.

**Comment by djouallah** [comment] 2023-03-12 04:31
same error with 0.8 :(

**Comment by JasperHG90** [comment] 2023-03-12 14:18
Same as @djouallah. I'm trying to execute:

```python
import deltalake as dk

dk.write_deltalake(
    "gs://my-bucket/tst", 
    my_df,
    storage_options={'SERVICE_ACCOUNT': '/path/to/sa_key.json'}
)
```

And I get result:

```
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?5857888a-952e-4991-ba5e-742ccd95f159)
---------------------------------------------------------------------------
PyDeltaTableError                         Traceback (most recent call last)
...
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>411.</b> <ins>That’s an error.</ins>
  <p>POST requests require a <code>Content-length</code> header.  <ins>That’s all we know.</ins>
", after 0 retries: HTTP status client error (411 Length Required) for url (https://storage.googleapis.com/storage/v1/b/data%2Dlake%2Dfeathered%2Dfrog/o/tst%2F%5Fdelta%5Flog%2F%5Fcommit%5F994c59b0%2D5ebf%2D4615%2D9b1f%2D163f7827ad11%2Ejson%2Etmp/copyTo/b/data%2Dlake%2Dfeathered%2Dfrog/o/tst%2F%5Fdelta%5Flog%2F00000000000000000000%2Ejson?ifGenerationMatch=0)
```

On GCP, the '/tst' folder exists on my bucket, but the `_delta_log` contains a json file with the following name: `_commit_994c59b0-5ebf-4615-9b1f-163f7827ad11.json.tmp`

**Comment by wjones127** [comment] 2023-03-12 18:03
Yes we haven't solved this issue yet. I've sunk a couple hours trying to figure it out, but no fix yet.

As I recall, I can't reproduce using the underlying object store; it only happens when we are writing a delta table. Even if I use the exact same function parameters, the exact same path, and the same data in the object store, I can't reproduce with just the object store. So something very weird is going on.

**Comment by wjones127** [comment] 2023-04-08 19:05
I've confirmed this will be fixed in the next version, thanks to the upstream fix https://github.com/apache/arrow-rs/pull/3921.

**Closed by wjones127** 2023-04-08 19:05 UTC
Labels: bug

**Comment by djouallah** [comment] 2023-05-07 01:57
@wjones127 thank you, it works
