### ISSUE TITLE
Make sure invariants are handled properly throughout the codebase

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1870] opened 2023-11-16 17:19 UTC
The invariant functionality should already be in the codebase.  we need to make sure enablement is handled properly acccording to 3/7 spec and that all code paths honor that.

**Comment by ion-elgreco** [comment] 2023-11-26 14:52
Seems to be duplicate of this one: https://github.com/delta-io/delta-rs/issues/1880

**Closed by ion-elgreco** 2023-11-26 14:52 UTC
Labels: enhancement
