### ISSUE TITLE
Running on EKS with IRSA results in _internal.DeltaError: Generic error: error in DynamoDb

### ISSUE THREAD

**Issue by danielgafni** [delta-io/delta-rs#2479] opened 2024-05-03 20:31 UTC
# Environment

**Delta-rs version**: 0.17.3

**Binding**:  Python

**Environment**: Kubernetes (EKS)
- **Cloud provider**: AWS
- **OS**: Ubuntu
- **Other**:

***
# Bug

**What happened**:
It seems like `deltalake` fails to utilize the environment variables provided to the pod: 

```
      AWS_STS_REGIONAL_ENDPOINTS:            regional
      AWS_DEFAULT_REGION:                    us-west-1
      AWS_REGION:                            us-west-1
      AWS_ROLE_ARN:                          arn:aws:iam::xxx:role/eks-my-role
      AWS_WEB_IDENTITY_TOKEN_FILE:           /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

writing a DeltaLake table to S3 with DynamoDB locking provider configured results in:

```python
_internal.DeltaError: Generic error: error in DynamoDb
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 465, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/execution/plan/execute_step.py", line 796, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dagster/_core/storage/upath_io_manager.py", line 446, in handle_output
    self.dump_to_path(context=context, obj=obj, path=path)
  File "/usr/local/lib/python3.11/site-packages/dagster_polars/io_managers/base.py", line 245, in dump_to_path
    self.write_df_to_path(context=context, df=df, path=path)
  File "/usr/local/lib/python3.11/site-packages/dagster_polars/io_managers/delta.py", line 220, in write_df_to_path
    df.write_delta(
  File "/usr/local/lib/python3.11/site-packages/polars/dataframe/frame.py", line 3881, in write_delta
    write_deltalake(
  File "/usr/local/lib/python3.11/site-packages/deltalake/writer.py", line 266, in write_deltalake
    table.update_incremental()
  File "/usr/local/lib/python3.11/site-packages/deltalake/table.py", line 1173, in update_incremental
    self._table.update_incremental()
```
Here are more detailed logs with `RUST_LOG=DEBUG`: 

```
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator::endpoints] resolving endpoint endpoint_params=EndpointResolverParams(TypeErasedBox[!Clone]:Params { region: Some("us-west-1"), use_dual_stack: false, use_fips: false, endpoint: None }) endpoint_prefix=None
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator::endpoints] will use endpoint Endpoint { url: "https://dynamodb.us-west-1.amazonaws.com/", headers: {}, properties: {} }
[2024-05-03T16:48:58Z INFO  tracing::span] lazy_load_identity;
[2024-05-03T16:48:58Z DEBUG deltalake_aws::credentials] provide_credentials; provider=default_chain
[2024-05-03T16:48:58Z DEBUG aws_config::meta::credentials::chain] load_credentials; provider=Environment
[2024-05-03T16:48:58Z DEBUG aws_config::meta::credentials::chain] provider in chain did not provide credentials provider=Environment context=the credential provider was not enabled: environment variable not set (CredentialsNotLoaded(CredentialsNotLoaded { source: Some("environment variable not set") }))
[2024-05-03T16:48:58Z DEBUG aws_config::meta::credentials::chain] load_credentials; provider=Profile
[2024-05-03T16:48:58Z DEBUG aws_runtime::fs_util] loaded home directory src="HOME"
[2024-05-03T16:48:58Z DEBUG aws_runtime::env_config::source] load_config_file; file=Default(Config)
[2024-05-03T16:48:58Z DEBUG aws_runtime::env_config::source] performing home directory substitution home="/root" path="~/.aws/config"
[2024-05-03T16:48:58Z DEBUG aws_runtime::env_config::source] home directory expanded before="~/.aws/config" after="/root/.aws/config"
[2024-05-03T16:48:58Z DEBUG aws_runtime::env_config::source] config file not found path=~/.aws/config
[2024-05-03T16:48:58Z DEBUG aws_runtime::env_config::source] config file loaded path=Some("/root/.aws/config") size=0
[2024-05-03T16:48:58Z DEBUG aws_runtime::env_config::source] load_config_file; file=Default(Credentials)
[2024-05-03T16:48:58Z DEBUG aws_runtime::env_config::source] performing home directory substitution home="/root" path="~/.aws/credentials"
[2024-05-03T16:48:58Z DEBUG aws_runtime::env_config::source] home directory expanded before="~/.aws/credentials" after="/root/.aws/credentials"
[2024-05-03T16:48:58Z DEBUG aws_runtime::env_config::source] config file not found path=~/.aws/credentials
[2024-05-03T16:48:58Z DEBUG aws_runtime::env_config::source] config file loaded path=Some("/root/.aws/credentials") size=0
[2024-05-03T16:48:58Z DEBUG aws_config::meta::credentials::chain] provider in chain did not provide credentials provider=Profile context=the credential provider was not enabled (CredentialsNotLoaded(CredentialsNotLoaded { source: None }))
[2024-05-03T16:48:58Z DEBUG aws_config::meta::credentials::chain] load_credentials; provider=WebIdentityToken
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator] invoke; service=sts operation=AssumeRoleWithWebIdentity
[2024-05-03T16:48:58Z DEBUG tracing::span] apply_configuration;
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator] timeout settings for this operation: TimeoutConfig { connect_timeout: Disabled, read_timeout: Disabled, operation_timeout: Disabled, operation_attempt_timeout: Disabled }
[2024-05-03T16:48:58Z DEBUG tracing::span] try_op;
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime_api::client::interceptors::context] entering 'serialization' phase
[2024-05-03T16:48:58Z DEBUG tracing::span] serialization;
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime_api::client::interceptors::context] entering 'before transmit' phase
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::retries::strategy::standard] no client rate limiter configured, so no token is required for the initial request.
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator] retry strategy has OKed initial request
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator] beginning attempt #1
[2024-05-03T16:48:58Z DEBUG tracing::span] try_attempt;
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator::endpoints] resolving endpoint endpoint_params=EndpointResolverParams(TypeErasedBox[!Clone]:Params { region: None, use_dual_stack: false, use_fips: false, endpoint: None, use_global_endpoint: false }) endpoint_prefix=None
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator] encountered orchestrator error; halting
[2024-05-03T16:48:58Z DEBUG tracing::span] finally_attempt;
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::retries::strategy::standard] attempt #1 succeeded, no retry necessary
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator] a retry is either unnecessary or not possible, exiting attempt loop
[2024-05-03T16:48:58Z DEBUG tracing::span] finally_op;
[2024-05-03T16:48:58Z WARN  aws_config::web_identity_token] STS returned an error assuming web identity role error=dispatch failure: other: Invalid Configuration: Missing Region (DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: ResolveEndpointError { message: "Invalid Configuration: Missing Region", source: None }, connection: Unknown } }))
[2024-05-03T16:48:58Z WARN  aws_config::meta::credentials::chain] provider failed to provide credentials provider=WebIdentityToken error=an error occurred while loading credentials: dispatch failure: other: Invalid Configuration: Missing Region (ProviderError(ProviderError { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: ResolveEndpointError { message: "Invalid Configuration: Missing Region", source: None }, connection: Unknown } }) }))
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::identity::cache::lazy] loaded identity
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator] encountered orchestrator error; halting
[2024-05-03T16:48:58Z DEBUG tracing::span] finally_attempt;
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::retries::strategy::standard] attempt #1 succeeded, no retry necessary
[2024-05-03T16:48:58Z DEBUG aws_smithy_runtime::client::orchestrator] a retry is either unnecessary or not possible, exiting attempt loop
[2024-05-03T16:48:58Z DEBUG tracing::span] finally_op;
```

I did run `aws sts get-caller-identity` in the very same container and it worked fine. 

**What you expected to happen**:

Previously I was successfully using `deltalake 0.16.3` with the same EKS setup. I believe this is a regression in one of the recently released versions. I haven't identified the exact regression point yet.

**How to reproduce it**:
Try writing a DeltaLake table on S3 from a EKS pod with IRSA configured. 

**More details**:
Tagging my friend @ion-elgreco

**Comment by ion-elgreco** [comment] 2024-05-04 09:05
@mightyshazam maybe you have an idea? Since you have been touching the S3 implementation recently

**Comment by danielgafni** [comment] 2024-05-04 10:53
Can confirm the issue does not exist on 0.16.3

**Comment by mightyshazam** [comment] 2024-05-04 16:43
@danielgafni Looks like the region provider isn't working. It looks like there was some necessary code in the AWS SDK that looked like an unnecessary hack that I missed. I have pushed a [new branch](https://github.com/mightyshazam/delta-rs/tree/aws-region-for-dynamo) to my fork. I don't have an AWS setup to test against, so I will need some time to make that work. However, if you have the ability to run that local version as an experiment, I can confirm and PR it.

**Comment by vegarsti** [comment] 2024-05-07 06:16
We have the exact same problem. We upgraded from https://github.com/delta-io/delta-rs/commit/9a7ee6f5c65287f160d1c9dfec8d41846d36059f (after the switch from Rusoto to the AWS SDK) and all AWS operations were working fine) to v0.17.3 yesterday and got this exact same problem.

@mightyshazam I have tried your branch with an AWS setup now, and it worked perfectly! The only thing we did was upgrade to your branch, on this commit https://github.com/mightyshazam/delta-rs/commit/1cf2b3142231e0a3d313d273210b0d07a5c4b47a. The region provider works again. So hope you can get it merged quickly!

Let me know if you need any more details and I'd be happy to provide.

**Comment by vegarsti** [comment] 2024-06-07 08:12
After upgrading delta-rs again to a recent commit (12d498ecb73242120070021d9cbac7796bc0b8ca) this has resurfaced. @mightyshazam is it possible that it's this commit? https://github.com/delta-io/delta-rs/pull/2500

**Comment by mightyshazam** [comment] 2024-06-07 12:39
> After upgrading delta-rs again to a recent commit ([12d498e](https://github.com/delta-io/delta-rs/commit/12d498ecb73242120070021d9cbac7796bc0b8ca)) this has resurfaced for us. @mightyshazam is it possible that it's this commit? #2500

Do you have logs and the configuration provided?

**Comment by vegarsti** [comment] 2024-06-07 12:43
> > After upgrading delta-rs again to a recent commit ([12d498e](https://github.com/delta-io/delta-rs/commit/12d498ecb73242120070021d9cbac7796bc0b8ca)) this has resurfaced for us. @mightyshazam is it possible that it's this commit? #2500
> 
> Do you have logs and the configuration provided?

Yes! What logs and config do you need?

**Comment by mightyshazam** [comment] 2024-06-07 12:45
The same info as the original post should be enough.

**Comment by vegarsti** [comment] 2024-06-07 12:56
Config from the k8s pod
```
    Environment:
      AWS_STS_REGIONAL_ENDPOINTS:   regional
      AWS_DEFAULT_REGION:           eu-west-1
      AWS_REGION:                   eu-west-1
      AWS_ROLE_ARN:                 arn:aws:iam::xxx:role/my-role
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jm448 (ro)
```

Logs (sorry, this is kinda messy!)
```
called `Result::unwrap()` on an `Err` value: ObjectStore { source: Generic { store: "S3", source: Client { status: 400, body: Some("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Token-0> snip </Token-0><RequestId>HVHG9KEJXYFQ5RJJ</RequestId><HostId>xGjeZ2Ww8TeQnFHdb23acGyZYJ03QfK9TwqUMYZAQxWDVNTd2cuQV5fggiuf0beyzlQm40ZHycA=</HostId></Error>") } } }
```

**Comment by vegarsti** [comment] 2024-06-10 15:57
Was unable to get any more logs even with trace level.

```
- Failed to read delta log object: Generic S3 error: Client error with status 400 Bad Request:
- <Error><Code>ExpiredToken</Code><Message>The provided token has expired. ...
```

**Comment by mightyshazam** [comment] 2024-06-11 16:41
@vegarsti  I would need to see a larger code sample, but I have a theory.  I see this snippet of code
```
pub async fn get_aws_storage_options(delta_lock_table_name: String) -> HashMap<String, String> {
    let credentials = AWS_PROVIDER.provide_credentials().await.unwrap();
```
This leads me to believe, the process is using the `AWS_PROVIDER` to extract the access and secret keys from the credentials object. In the case that those keys are environment variables, it would work just fine in perpetuity. In the case that they are coming from any other sources, such as IMDS, the access and secret keys would expire.
If those expiring keys are passed as credentials in the storage options, once they expire, things would stop working. If you just pass `AWS_EC2_METADATA_DISABLED: false` as a storage option, it will use the default credential chain and support the rotation of the credentials.

**Comment by vegarsti** [comment] 2024-06-11 17:04
That is an excellent tip! I will try that. Thank you!

**Comment by vegarsti** [comment] 2024-06-12 05:39
Like this right, in the hash map of options? It fails in the same way unfortunately 😢 

```
        ("AWS_EC2_METADATA_DISABLED".to_string(), "false".to_string()),
```

**Comment by ion-elgreco** [comment] 2024-06-12 10:55
@mightyshazam also on our latest release it still emitting warnings 

[2024-06-12T10:54:33Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: io error: error trying to connect: tcp connect error: No route to host (os error 113): tcp connect error: No route to host (os error 113): No route to host (os error 113) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Io, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 113, kind: HostUnreachable, message: "No route to host" })), connection: Unknown } }) }))
[2024-06-12T10:54:34Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: timeout: error trying to connect: HTTP connect timeout occurred after 1s: HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 1s }), connection: Unknown } }) }))

**Comment by mightyshazam** [comment] 2024-06-12 11:03
> @mightyshazam also on our latest release it still emitting warnings, albeit 2 less than before ; )
> 
> ```
> [2024-06-12T10:54:33Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: io error: error trying to connect: tcp connect error: No route to host (os error 113): tcp connect error: No route to host (os error 113): No route to host (os error 113) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Io, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 113, kind: HostUnreachable, message: "No route to host" })), connection: Unknown } }) }))
> [2024-06-12T10:54:34Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: timeout: error trying to connect: HTTP connect timeout occurred after 1s: HTTP connect timeout occurred after 1s: timed out (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Timeout, source: hyper::Error(Connect, HttpTimeoutError { kind: "HTTP connect", duration: 1s }), connection: Unknown } }) }))
> ```

Are you using the catalog feature? I noticed the code there also uses the AWS sdk, and it is using the default behavior?

**Comment by ion-elgreco** [comment] 2024-06-12 11:06
@mightyshazam no just a custom s3 endpoint with LakeFS, nothing else

**Comment by mightyshazam** [comment] 2024-06-12 12:33
@vegarsti are you still passing the secret and access keys in the options map? If so, you need to remove those. You should be able to remove the `AWS_PROVIDER` reference entirely.

**Comment by vegarsti** [comment] 2024-06-12 12:36
> @vegarsti are you still passing the secret and access keys in the options map? If so, you need to remove those. You should be able to remove the `AWS_PROVIDER` reference entirely.

Oh hey, thanks! I was indeed doing that. I tried a few more things, like removing the provider, but I kept the access keys.

**Comment by vegarsti** [comment] 2024-06-13 06:55
@mightyshazam This worked! Thank you so much! Logs have been saying that we've been using Static credential provider, but after removing the access key and secret (and AWS_EC2_METADATA_DISABLED to false), it now says WebIdentity, which seems like is what we want.

**Comment by ion-elgreco** [comment] 2024-06-13 07:01
@vegarsti so this issue is resolved then?

**Comment by vegarsti** [comment] 2024-06-13 07:08
Indeed!

**Closed** 2024-06-13 07:09 UTC
Labels: bug, binding/rust, storage/aws
