### ISSUE TITLE
Programmatic configuration of Azure storage options in `deltalake.DeltaTable`

### ISSUE THREAD

**Issue by malmgrek** [delta-io/delta-rs#767] opened 2022-08-23 18:12 UTC
# Description

Currently (as of version `0.5.8`) configuring Azure ADLS Gen2 storage options is only supported via environment variables

- `AZURE_STORAGE_ACCOUNT_NAME`
- `AZURE_STORAGE_ACCOUNT_KEY`

To allow cleaner and more functional applications, ability to configure Azure in `DeltaTable` through the instance parameters would be great. For example, the high level API could be

```
dt = DeltaTable(
    storage_options={
        "AZURE_STORAGE_ACCOUNT_NAME": "accountname",
        "AZURE_STORAGE_ACCOUNT_KEY: "foobar",
    }
)
```

Moreover, alternative authentication secrets could be supported analogously, for example

```
dt = DeltaTable(
    storage_options={
        "AZURE_STORAGE_ACCOUNT_NAME": "accountname",
        "AZURE_STORAGE_SAS_TOKEN: "baztest",
    }
)
```

And so on.

**Related Issue(s)**
- #766

**Comment by roeap** [comment] 2022-09-01 11:31
@malmgrek - with the `0.6` release, configuration using storage options should now be possible. Could you confirm that?

**Comment by jayaro-work** [comment] 2022-09-02 21:30
I'm trying to connect to ADLS Gen 2 using the storage_options but it is not working for me. I'm using Account Name, Account Key, and Connection String and not luck. Also, where do you use the container name? in the DeltaTable path?

**Comment by roeap** [comment] 2022-09-02 21:38
from 0.6 on something like that should work: 

```py
dt = DeltaTable(
    "az://<container>/<path to table>",
    storage_options={
        "AZURE_STORAGE_ACCOUNT_NAME": "accountname",
        "AZURE_STORAGE_ACCOUNT_KEY: "foobar",
    }
)
```

The storage options can also be set via the environment.

**Comment by jayaro-work** [comment] 2022-09-02 21:52
@roeap Awesome it is working now. Thanks!

dt.schema() and dt.history() works, but to_pandas, to_pyarrow_table, and to_pyarrow_dataset all give the following error.

Failed to read delta log object: Generic MicrosoftAzure error: Account must be specified

**Comment by roeap** [comment] 2022-09-06 16:26
> Failed to read delta log object: Generic MicrosoftAzure error: Account must be specified

This measn the azure account is not configured. You can do this via the environment `AZURE_STORAGE_ACCOUNT_NAME`, or passed within the storage options.

**Comment by roeap** [comment] 2022-09-06 16:28
@malmgrek - could you confirm if this is resolved now?

**Comment by jayaro-work** [comment] 2022-09-06 17:18
@roeap I got a different message on 0.6.1 (see below). I opened the individual file and it has data so I'm unsure what could be causing this.

PanicException: should be URL safe: EmptySegment { path: "/delta-lake/part-00000-612a5ac2-1520-4639-bfec-00da6eda8e31.c000.snappy.parquet" }

**Comment by roeap** [comment] 2022-09-06 17:20
hmm .. which string do you use to load the table? The object store implementation is quite strict on characters etc. The message suggests it encountered non url safe characters. But the sting in the error message looks fine.

**Comment by jayaro-work** [comment] 2022-09-06 17:27
@roeap it seems there is an entry with Asian characters in the log for that file (shown below). That is probably what is causing the issue then.

\"assetId\":\"玻利维亚ES28公路-FAJ12665\"

**Comment by roeap** [comment] 2022-09-06 17:29
Is there a way for you to share that log entry? Then I could try and reproduce the issue.

**Comment by jayaro-work** [comment] 2022-09-06 18:08
@roeap my apologies, it was my mistake, I was ending the path with "/" and that was causing the issue. Now it is working.

Thanks so much for all the help and prompt responses!

**Comment by roeap** [comment] 2022-09-07 06:01
@malmgrek - could you check if this works for you using `0.6.1`?

**Comment by malmgrek** [comment] 2022-09-07 07:34
@roeap - sorry for the delay, now back to work. Tried with `0.6.1` but I am getting an error:

`deltalake.PyDeltaTableError: Not a Delta table: No snapshot or version 0 found, perhaps az://<mycontainer>/<mydir1>/<mydir2> is an empty dir?`

Although I didn't change the URI. Maybe I am missing something, did the URI parameter expected format change...

**Comment by roeap** [comment] 2022-09-07 07:38
hmm .. we have several cases now, where the azure integration works. Since it used to work I assume there is a valid delta log at that location.

Is there maybe a trailing `/`, which i think is another regression, that we can no longer handle that. But the message should definately be more telling.. Also, is the environment for the account configured correctly, or are you passing that in.

**Comment by malmgrek** [comment] 2022-09-07 07:43
- No trailing forward slash
- I am now passing `storage_options` to `DeltaTable` at initialization time (removed environment variables from code)
- However, I also tested with the old environment variables approach and got the same error with `0.6.1` whereas all good with `0.5.7`

**Comment by malmgrek** [comment] 2022-09-07 07:45
Are there perhaps some changes on how the URI is manipulated under the hood before passing to Azure ADLS API?

**Comment by roeap** [comment] 2022-09-07 07:49
we use a completely different backend to handle connecting to object stores, so yes :) In fact teh new backend is quite strict about path safety / path handling ....

What specifically are you specifiying? key, or identity? Are there any more specific you can share about the path? Special or non-url safe character o.a.?

**Comment by malmgrek** [comment] 2022-09-07 07:55
Okay I see,

Code that is working on `deltalake==0.5.7`

```
# AZURE_STORAGE_ACCOUNT_NAME and AZURE_STORAGE_ACCOUNT_KEY are set
# as environmen variables
dt = DeltaTable(
    "adls2://foobarstorage/dirfoo/dirbar/my_delta_table"
)
```

Code that isn't working on `deltalake==0.6.1`

```
dt = DeltaTable(
    "az://foobarstorage/dirfoo/dirbar/my_delta_table",
    storage_options={
        "AZURE_STORAGE_ACCOUNT_NAME": "foobarstorage",
        "AZURE_STORAGE_ACCOUNT_KEY": "randomstring"
    }
)
```

**Comment by malmgrek** [comment] 2022-09-07 08:03
I think I found out.

Whereas 
```
dt = DeltaTable("adls2://foobarstorage/dirfoo/dirbar/my_delta_table")
```
was the expected format in `0.5.7`, in `0.6.1` it works without the `AZURE_STORAGE_ACCOUNT_NAME` (`"foobarstorage"` above) in the beginning of the URI query, that is
```
dt = DeltaTable(
    "az://dirfoo/dirbar/my_delta_table",
    storage_options={
        "AZURE_STORAGE_ACCOUNT_NAME": "foobarstorage",
        "AZURE_STORAGE_ACCOUNT_KEY": "randomstring"
    }
)
```

**Comment by roeap** [comment] 2022-09-07 08:08
Yes, should have thougth of that! The `adls2` scheme was invented here, but inconsistent with all the other schemes out there. We now aliged with fsspec. and some more ones ... https://delta-io.github.io/delta-rs/python/usage.html#loading-a-delta-table

Does this mean it works now and we can close this? 😄

**Comment by malmgrek** [comment] 2022-09-07 09:48
Yes :tada:

**Closed** 2022-09-07 09:50 UTC
Labels: enhancement
