### ISSUE TITLE
Implement vacuum command

### ISSUE THREAD

**Issue by xianwill** [delta-io/delta-rs#97] opened 2021-03-01 14:12 UTC
delta-rs should have a "vacuum table" utility analogous to the one provided by the [open source Spark Delta Lake implementation](https://docs.delta.io/latest/delta-utility.html#remove-files-no-longer-referenced-by-a-delta-table). This utility is useful for cleaning up old files that are no longer referenced by the delta log (e.g. files rewritten by merge statements, optimize command etc.).

See the [VacuumCommand](https://github.com/delta-io/delta/blob/40182f3de69ca083afd48ef522897519d36e5fab/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala) in the open source implementation for reference.

**Comment by rtyler** [comment] 2021-05-17 02:32
@fvaleye I think this is actually done right? I'm not clear what work we have left to do

**Comment by fvaleye** [comment] 2021-05-17 07:12
> @fvaleye I think this is actually done right? I'm not clear what work we have left to do

Yes, it is already implemented! Hum, we need to improve the tests suite: https://github.com/delta-io/delta-rs/issues/227

**Comment by MironAtHome** [comment] 2021-11-03 11:11
Как насчет поправить документацию?
Наверное стоит подновить с вот этого
![image](https://user-images.githubusercontent.com/18360184/140049963-8e265274-7faf-4c8c-b70d-325501400845.png)
на вот это?
![image](https://user-images.githubusercontent.com/18360184/140050299-8bddf34b-6994-4be0-953d-200724b3621a.png)

**Comment by mrk-its** [comment] 2022-07-03 21:23
@rtyler @fvaleye It looks like there are still two serious issues with vacuum implementation:
* vacuum lists all files in dataset using `StorageBackend.list_objs`. The problem is this function returns all files (including these in subdirectories) on `s3` backend and `gcs` backend (althrough I'm not sure about gcs). On `file` and `azure` backends this function  lists only first-level files (without recursing to subdirectories). 
* vacuum ignores files not referenced by delta log at all (so not included on DeltaTableState.files() and DeltaTableState.all_tombstones() lists)

**Comment by wjones127** [comment] 2022-09-28 02:58
Resolved by #669.

**Closed** 2022-09-28 02:58 UTC
Labels: enhancement, good first issue, binding/rust
