### ISSUE TITLE
Can't delete from Spark DeltaLake table if it has a timestamp field

### ISSUE THREAD

**Issue by bhuacret** [delta-io/delta-rs#1478] opened 2023-06-20 00:26 UTC
# Environment

**Delta-rs version**:0.12.0
**Binding**: Rust

**Environment**:dev
- **Cloud provider**:Azure
- **OS**:Linux/Windows
- **Other**:

***
# Bug

**What happened**:
I'm trying to delete some data from a delta table in Rust, using with_predicate.

`    let (table,_) = DeltaOps(table).delete().with_predicate(col("fechabloqueo").eq(cast(lit("2022-11-06"),Date32))).await.unwrap();   `

but im getting `"Execution error: Failed to map column projection for field fechacreacion. Incompatible data types Timestamp(Nanosecond, None) and Timestamp(Microsecond, None)"` 

**What you expected to happen**:

Delete successfully with that condition.

**How to reproduce it**:

**More details**:
The table was created using default INT96 outputTimestampType option. 

If i rewrite the table using `spark.conf.set("spark.sql.parquet.outputTimestampType", "TIMESTAMP_MICROS")` 
still fails:
`"Execution error: Failed to map column projection for field fechacreacion. Incompatible data types Timestamp(Microsecond, Some(\"UTC\")) and Timestamp(Microsecond, None)"`

**Comment by cmackenzie1** [comment] 2023-06-21 17:03
Out of curiosity, is `spark.sql.parquet.timestampNTZ.enabled` set to true of false?

**Comment by bhuacret** [comment] 2023-06-21 20:37
Just tested with both `spark.sql.parquet.timestampNTZ.enabled` true and false at Spark 3.4.0, i keep getting the same error.

**Comment by Blajda** [comment] 2023-06-29 03:02
This is caused by ambiguity on how to store timestamps in the serialization section of the protocol. The older version of the protocol specified that timestamp columns do not specified the timezone but [this change](https://github.com/delta-io/delta/commit/cbc68db811c7008dff4869335f41188e937577e4#diff-62d56fa1c25dda8d49ccdbf9ea31df4576f84625706d54613dff0acc8f974d97L1032) has modified it to be adjusted to UTC.

I did some local testing. Updating the code [here](https://github.com/delta-io/delta-rs/blob/main/rust/src/delta_arrow.rs#L125-L128) to include the timezone of UTC and performing of casts in the user supplied query (e.g `(cast(lit("2022-11-06"),arrow_schema::DataType::Timestamp(arrow_schema::TimeUnit::Microsecond, Some("UTC".into()))))` will fix this issue. I'm just not certain if this change is a breaking change.

related: https://github.com/delta-io/delta/issues/643

**Comment by ion-elgreco** [comment] 2024-08-19 19:57
Resolved by https://github.com/delta-io/delta-rs/pull/2615

**Closed by ion-elgreco** 2024-08-19 19:57 UTC
Labels: bug
